### ISSUE TITLE
Tasarım düzeltmeleri

### ISSUE THREAD

**Issue by selmansamet** [afocustech/afocus.tech#1]
- [x] Menü elemanları uppercase yapılacak
- [x] Genel font değişecek

**Comment by mahmutcanusta** [comment]
- [ ] Ekip kısmı arka planı gradient yatay değil çapraz olacak, daha soft tonlar kullanılacak.
- [ ] Footer sosyal medya ikonlarına hover eklenecek.
- [ ] Menü gradient kısmı yatay değil çapraz geçiş olacak.
- [ ] Menülerin hangi elemanı aktifse o arka planı beyaz yazısı siyah şekilde olacak. (Boxed)

**Comment by mahmutcanusta** [comment]
- [ ] Menü altına gölge verilecek.

**Comment by mahmutcanusta** [comment]
- [ ] Ekip kısmında kullanıcı altına sosyal medya ikonları eklenecek.
- [ ] Ekip kısmı square 5px radiuslu olacak.

**Comment by selmansamet** [comment]
5fca84dff4467e967cd9efad261edeedc0aa79e4

**Comment by mahmutcanusta** [comment]
- [ ] Sosyal medya ikonları hover'ı eklenecek. (insta, skype, linkedin, facebook vb.)
